name: Create Release Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag name (e.g., v1.0.0)"
        required: true
      title:
        description: "Release title"
        required: false
      notes:
        description: "Release notes (optional)"
        required: false

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ github.event.inputs.title || github.event.inputs.tag }}
          body: ${{ github.event.inputs.notes || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
